# Generated by Django 4.0.4 on 2022-05-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_familia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('vinculo', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='familia',
        ),
    ]
