# Generated by Django 4.0.5 on 2022-06-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_familia', '0003_apellido_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apellido',
            name='Pais',
            field=models.CharField(max_length=40),
        ),
    ]
