# Generated by Django 4.0.5 on 2022-06-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_familia', '0004_alter_apellido_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='calle',
            field=models.CharField(max_length=40),
        ),
    ]
