# Generated by Django 4.0.5 on 2022-06-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_familia', '0005_alter_domicilio_calle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='viviendo_desde',
            field=models.DateField(null=True),
        ),
    ]
