# Generated by Django 4.0.5 on 2022-07-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_familia', '0007_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='Nombre',
        ),
    ]
